repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff-check
        args: [--fix, --config=lab06/task02/pyproject.toml]
        files: ^lab06/task02/
      - id: ruff-format
        args: [--check, --config=lab06/task02/pyproject.toml]
        files: ^lab06/task02/

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: bash -c 'cd lab06/task02 && uv run pyright'
        language: system
        types: [python]
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: bash -c 'cd lab06/task02 && uv run pytest'
        language: system
        pass_filenames: false
        stages: [pre-push]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.9
    hooks:
      - id: commitizen
        stages: [commit-msg]
